### ISSUE TITLE
Add "CalorieNinjas" API

### ISSUE THREAD

**Issue by calorieninjas** [APIs-guru/openapi-directory#747]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.calorieninjas.com/openapi.json
**Name**: CalorieNinjas

**Comment by MikeRalphson** [comment]
Thanks for the contribution. The API definition looks to have been modified from the petstore demo and still has references to "Pet"s within it. References to `#/components/schemas/Pet` means the API definition fails to validate. Could you take a look?

**Comment by calorieninjas** [comment]
Okay I updated the openapi.json schema. Please let me know if there's anything else that needs to be fixed.

**Comment by MikeRalphson** [comment]
Thanks, I still see this error:

> Cannot resolve reference: #/components/schemas/Pet
#/components/requestBodies/Pet/content/application~1json/schema/%24ref

**Comment by calorieninjas** [comment]
The schema no longer contains any references to Pet and the URL . Is there any caching that needs to be cleared or maybe a re-fetch of the schema from the URL?

**Comment by MikeRalphson** [comment]
It still had Pet references when I re-fetched it. That seems to be resolved now, but there is at least one other error in your API definition:

> path parameters must appear in the path
#/paths/~1nutrition/get/parameters/0

I'm unsure if your `paths` key should be `/nutrition/{query}` or the `query` parameter should be `in: query` not `in: path`

Also the `maxLength` value must be a number not a string, and the `maxLength` property itself must appear within the parameter `schema` object.

**Comment by calorieninjas** [comment]
Okay I updated it again. It seems to pass this online validator: https://apitools.dev/swagger-parser/online/

**Comment by MikeRalphson** [comment]
I now see this error:

> Could not dereference securityScheme x-api_key
#/security

`x-api-key` is spelled `x-api_key` in one place, both need to match.

**Comment by calorieninjas** [comment]
Fixed.

**Comment by MikeRalphson** [comment]
Ok, still seeing the error so there is obviously some server-side caching involved, Will check again shortly.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
